### ISSUE TITLE
TypeError: gitChangedFiles is not a function

### ISSUE THREAD

**Issue by NetanelBasal** [kreuzerk/import-conductor#16]
Hi Kevin,

When running the command with the `--staged` flag, it throws `TypeError: gitChangedFiles is not a function`. That's happening because the `gitChangedFiles` is the [default](https://github.com/kreuzerk/import-conductor/blob/master/src/index.ts#L200) library's export. 

When changing it the `gitChangedFiles.default()` it works. The issue is in this [line](https://github.com/kreuzerk/import-conductor/blob/master/src/index.ts#L5). The `*` should be removed.

**Comment by kreuzerk** [comment]
Awesome! Thx for creating this issue and the research! Will try to fix this soon

**Comment by kreuzerk** [comment]
Should be fixed with version 1.4.4. Thx for reporting this. Let me know if somethings not working yet.

**Comment by NetanelBasal** [comment]
It works great, thanks. I'd also consider adding a `--silent` option.
