### ISSUE TITLE
Add exclude option

### ISSUE THREAD

**Issue by shaharkazaz** [kreuzerk/import-conductor#20]
Allow excluding files/paths in the following ways:
* Add a new config property `ignore` which accepts file paths/glob regexes.
* Detect and ignore via a comment in the file: `// import-conductor-ignore`

**Comment by pyrrhicman** [comment]
Hi, Thanks for this awesome library, I already integrated it with File watcher of my IDE Webstorm which runs it on save. 
although I faced a problem which this enhancement will fix it.
in a Typescript project I use TypeDi for dependency injection and I need to `reflect-metadata` be the first line but after running the plugin it will be pushed to third line.
```
import 'reflect-metadata';
```
I'll be eagerly waiting for this ☺️
