### ISSUE TITLE
Custom imports are not categorised correctly

### ISSUE THREAD

**Issue by cgatian** [kreuzerk/import-conductor#21]
Sorry in advance for the super generic title. 

If I try running your demo import
```typescript
import { Component, OnInit } from '@angular/core';
import { CustomerService } from './customer.service';
import { Customer } from './customer.model';
import { Order } from '../order/order.model';
import { LoggerService } from '@myorg/logger';
import { Observable } from 'rxjs';
```
My output is:

```typescript
import { Order } from '../order/order.model';
import { Component, OnInit } from '@angular/core';
import { LoggerService } from '@myorg/logger';
import { Observable } from 'rxjs';

import { Customer } from './customer.model';
import { CustomerService } from './customer.service';
```

Command running the importer:
```bash
import-conductor -s test.ts -p @myorg
```

~~I am running this on Windows. Perhaps that's the issue?~~

If I pin the version to 1.4.4 it outputs as expected.

**Comment by cgatian** [comment]
If I pin to 1.4.0 it works!

**Comment by shaharkazaz** [comment]
@cgatian do you actually have `@angular/core` & `rxjs` as dependencies? `import-conductor` is extracting the 3rd party libs from your package/package-lock files.

**Comment by cgatian** [comment]
OOO I didnt know it had smarts! Sorry about that. I just ran it against a single file. Yeah I was struggling to get the custom user ones to work properly they ended up in "imports from other modules or directories in your codebase".

**Comment by shaharkazaz** [comment]
@cgatian I added smarts in v1.5.0 😉 
Ya, that's the bug I was referring to.
