### ISSUE TITLE
barred o imports cause extra semi-colon

### ISSUE THREAD

**Issue by cgatian** [kreuzerk/import-conductor#24]
Imports using a barred o (Ɵ) create an additional semicolon.

Original:
```typescript
import { ƟmyImport } from 'myLib';
```

Output:
```typescript
import { ƟmyImport } from 'myLib';;
```

**Comment by shaharkazaz** [comment]
@cgatian Does this still happen in v2.0.2?

**Comment by cgatian** [comment]
The extra ';' are no longer happening, but now I'm getting odd spacing between the imports. Could be related to #37 

![image](https://user-images.githubusercontent.com/1752170/92243374-675b6b80-ee8f-11ea-9607-53423bbf92b6.png)
![image](https://user-images.githubusercontent.com/1752170/92243514-9a9dfa80-ee8f-11ea-873e-8dd649422270.png)

**Comment by shaharkazaz** [comment]
@cgatian ok so closing this one 🙂 track #37 and see if it resolves your issue.
