### ISSUE TITLE
Second run adds extra new lines

### ISSUE THREAD

**Issue by Lonli-Lokli** [kreuzerk/import-conductor#37]
**Describe the bug**
Multiple run import-conductor adds extra new line on each run

**Steps to reproduce**
With this script run it again on file with different imports
"scripts": {
    "import-conductor": "import-conductor -p @myorg"
 },

**Expected behavior**
Second run should not change file

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - import conductor version: [e.g. v2] 2.0.2

**Comment by cgatian** [comment]
Amazing! Will give it a go

**Comment by cgatian** [comment]
@kreuzerk unfortunately I'm still seeing the issue on 2.0.3.

**Before:**
```typescript
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Injectable, Injector } from '@angular/core';
import { Observable } from 'rxjs';

import { MyTranslateService } from './translate.service';
```

After:
```typescript
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';

import { Injectable, Injector } from '@angular/core';

import { Observable } from 'rxjs';



import { MyTranslateService } from './translate.service';
```

**Comment by shaharkazaz** [comment]
@cgatian I can't reproduce this scenario in our playground & specs, please provide a reproduction.
