### ISSUE TITLE
Additional carriage returns between third-party imports

### ISSUE THREAD

**Issue by cgatian** [kreuzerk/import-conductor#42]
**Describe the bug**
This is a follow issue up per comment in #37 to create a minimal reproduction.
Extra lines are produced in the output

**Steps to reproduce**
Created a repository reproducing the behavior.
Clone: https://github.com/cgatian/ic-issue
`npm i`
`npm run conduct` (custom script for import-conductor)

**Expected behavior**
Produce intended output, per docs.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - import conductor version: 2.0.3

**Additional context**
```typescript
import { HttpEvent, HttpHandler, HttpRequest } from '@angular/common/http';
import { Injector } from '@angular/core';
import { Observable } from 'rxjs';

import { HyTranslateService } from './translate.service';

export class AcceptLanguageHeader {

  private _translateService!: HyTranslateService;

  constructor(private _injector: Injector) { }

  intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
      return {} as any;
  }
}
```
**Becomes:**
```typescript
import { HttpEvent, HttpHandler, HttpRequest } from '@angular/common/http';

import { Injector } from '@angular/core';

import { Observable } from 'rxjs';



import { HyTranslateService } from './translate.service';

export class AcceptLanguageHeader {

  private _translateService!: HyTranslateService;

  constructor(private _injector: Injector) { }

  intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
      return {} as any;
  }
}
```

![image](https://user-images.githubusercontent.com/1752170/93406020-a65cca00-f85c-11ea-990f-16f8be9a5bfa.png)

**Comment by cgatian** [comment]
@shaharkazaz Now that I've confirmed it at least happens outside my massive project. I'm hoping you could give the reproduction steps a shot to see if you also get a similar output. I'll fork the code tomorrow and see if I can make a unit test that produces similar results.

**Comment by kreuzerk** [comment]
Hi @cgatian thanks a lot for reporting this issue and the awesome reproduction steps. They are very nicely described and very helpful.

I cloned your repository and installed the latest version of import-conductor (2.0.3). The issue has been fixed. Means the output now looks correct:

````json
import { HttpEvent, HttpHandler, HttpRequest } from '@angular/common/http';
import { Injector } from '@angular/core';
import { Observable } from 'rxjs';

import { HyTranslateService } from './translate.service';

export class AcceptLanguageHeader {

  private _translateService!: HyTranslateService;

  constructor(private _injector: Injector) { }

  intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
      return {} as any;
  }
}
````

**Comment by kreuzerk** [comment]
@cgatian let us know if it works for you.
