### ISSUE TITLE
Simple-git dependency with high vulnerability

### ISSUE THREAD

**Issue by dionatan-g** [kreuzerk/import-conductor#69]
Hey, just want to point out that one of the import-conductor dependencies are giving me a warning about vulnerability.

![image](https://user-images.githubusercontent.com/44219120/160019846-c4816e38-2840-48c6-9577-ad5eed63adc5.png)

As I'm using it on a production code, would be cool to bump up this simple-git version if possible.

Thanks!

**Comment by dionatan-g** [comment]
Closing as it was fixed on https://github.com/kreuzerk/import-conductor/pull/68

**Comment by mtrefzer** [comment]
Do you have any idea when npm package will be updated with this fix?

**Comment by dionatan-g** [comment]
Probably on the next fix/feature, since chore doesn't increment version.
But yea, I need this aswell :D

**Comment by kreuzerk** [comment]
Yes, you are right usually chore fixes will not be released. I wanted to make this available as fast as possible and therefore just released v2.2.6 that contains the fix.
