### ISSUE TITLE
Bug: File content being deleted and replaced by "none" when there is no import statement

### ISSUE THREAD

**Issue by dionatan-g** [kreuzerk/import-conductor#78]
The problem happens when a file doesn't have an import statement and it tries to do something anyway and end up deleting all the file content.

- Create a typescript file without an import statment;
![image](https://user-images.githubusercontent.com/44219120/169036923-f6a8412f-b965-4e44-9ae3-627a9ac82b6f.png)
- Run import-conductor on this file:
![image](https://user-images.githubusercontent.com/44219120/169037016-1d9d8895-f83b-49d2-aa0a-0d1f8587c047.png)
- File content after:
![image](https://user-images.githubusercontent.com/44219120/169037099-db91dda5-22fe-4ad5-992a-8d6aed9dbd00.png)

 - OS: Windows 11
 - import conductor version: 2.4.0
 
As for the why i'm trying to run it on a file without imports? cuz it runs on the lint-staged hook with husky.

**Comment by ericaskari** [comment]
Faced the same issue

**Comment by gesielrosa** [comment]
I have the same issue

![Screen Shot 2022-06-01 at 17 16 29](https://user-images.githubusercontent.com/40439982/171493658-65ed8019-9069-4208-8e95-ebd275f88615.png)
