### ISSUE TITLE
Boost Performance With ‘fast-glob’ for Larger Projects

### ISSUE THREAD

**Issue by markoberholzer-es** [kreuzerk/import-conductor#88]
**Describe the feature**
We are using the import-conductor extensively for a larger mono-repo and are very happy with the results so far.

One thing we noticed however is that the time to complete for each commit is rather high (varying between `20s-50s`, depending on the dev's hardware).

I have taken some time to investigate the bottleneck and came to the conclusion that it is due to the fact that the `sync` method of the `glob` library takes that long (we are using the `--ignore` flag when we execute the `import-conductor` with wildcards set).

When swapping the `glob` library in favor of the `fast-glob` library, performance increases, so that the imports are conducted in a fraction of a second.

**New contributors to our project are always welcome**
I am happy to make a pull request, if you think that my suggestion will be of any benefit to your project.

**Comment by kreuzerk** [comment]
Hi @markoberholzer-es, wow, that sounds great! Yes, of course, a PR to improve the performance is more than welcome!

**Comment by markoberholzer-es** [comment]
Hi @kreuzerk  - many thanks for your reply. Tried to push my changes to a new branch, but I get a 403.

**Comment by markoberholzer-es** [comment]
Hi @kreuzerk - many thanks for your reply. Wonderful, I just created a new pull request with the proposed changes.

**Comment by kreuzerk** [comment]
Did you fork the repository?

**Comment by kreuzerk** [comment]
It's this PR, right? https://github.com/kreuzerk/import-conductor/pull/90/files

**Comment by kreuzerk** [comment]
There's still an issue with the deployment; I think it has to do with access tokens. Will take a look

**Comment by kreuzerk** [comment]
okay, fixed it. 2.6.0 is now out. Thx a lot for your help!

**Comment by markoberholzer-es** [comment]
Hi @kreuzerk - wow that was quick! - big thanks from my side as well :)
